### ISSUE TITLE
GPU Clock Control stuck

### ISSUE THREAD

**Issue by dkatzdev** [JamesCJ60/Universal-x86-Tuning-Utility-Handheld#10]
After setting a value with the iGPU manual clock control slider, disabling the feature leaves it locked at the last set speed instead of returning to automatic control as intended.

**Comment by JamesCJ60** [comment]
This is intended behaviour, as the APU’s SMU requires the system to either enter sleep or shutdown to reset itself.

**Comment by dkatzdev** [comment]
Even after reboot it persisted. I was able to fix it only by connecting the OEM charger recognized as "full power" which switched to the USB-PD Turbo profile. Using non OEM chargers didn't solve it.
