### ISSUE TITLE
Turning manual GPU clock off does not reset

### ISSUE THREAD

**Issue by buri-92** [JamesCJ60/Universal-x86-Tuning-Utility-Handheld#13]
I set a manual iGPU clock, which worked. I then disabled the setting expecting the GPU clock to go back to its default behavior, it didn't. The GPU was 'stuck' at the MHz I had set and the only way to reset was a system reboot.

I tested the non-Handheld version of the app afterwards and I am pretty sure, it behaves the same way.

**Comment by JamesCJ60** [comment]
Hi, this isn't a bug. This is just the normal behaviour AMD has given this specific function.

**Comment by buri-92** [comment]
Oh, ok. Thanks for the quick reply.
